### ISSUE TITLE
TexTools crashes when clicking on an item from the gear list

### ISSUE THREAD

**Issue by donniewoolsey** [TexTools/FFXIV_TexTools_UI#110]
When I search for an item and click in it the left list I get these three errors in succession before TexTools closes
*************************************************************************************************************************************

System.Configuration.ConfigurationErrorsException: Failed to save settings: An error occurred loading a configuration file: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden. (C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config) ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden. (C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config) ---> System.IO.IOException: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden.
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at FFXIV_TexTools.ViewModels.ModelViewModel.set_CullModeToggle(Boolean value)
   at FFXIV_TexTools.ViewModels.ModelViewModel.<UpdateModel>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.MainWindow.<UpdateViews>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

*********************************************************************************************************************************************

System.Configuration.ConfigurationErrorsException: Failed to save settings: An error occurred loading a configuration file: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden. (C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config) ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden. (C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config) ---> System.IO.IOException: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden.
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at FFXIV_TexTools.ViewModels.ModelViewModel.set_CullModeToggle(Boolean value)
   at FFXIV_TexTools.ViewModels.ModelViewModel.<UpdateModel>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.MainWindow.<UpdateViews>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

*********************************************************************************************************************************************

System.Configuration.ConfigurationErrorsException: Failed to save settings: An error occurred loading a configuration file: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden. (C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config) ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden. (C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config) ---> System.IO.IOException: Unable to open file 'C:\Users\Seelie\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.6.2\user.config' for writing because it is read-only or hidden.
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at FFXIV_TexTools.ViewModels.ModelViewModel.set_CullModeToggle(Boolean value)
   at FFXIV_TexTools.ViewModels.ModelViewModel.<UpdateModel>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.MainWindow.<UpdateViews>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FFXIV_TexTools.App.Main()

**Comment by captice** [comment]
Go to C:\Users\**YOUR NAME**\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_\2.3.6.2\
Right click on the user.config file and then pick Properties and turn off the Read-Only box and click Apply and OK.

**Comment by donniewoolsey** [comment]
Read-only was not selected.

**Comment by Squall-Leonhart** [comment]
turn off controlled folder access or add textools to the whitelist.

**Comment by KoraLyn** [comment]
Closing due to inactivity. Feel free to reopen if the issue persists.
