### ISSUE TITLE
Crash Report 2.3.1.8

### ISSUE THREAD

**Issue by GitKatz** [TexTools/FFXIV_TexTools_UI#21]
Every time I try to open textools, I get this error. It says I should report it as a bug, hopefully I'm at the right place: 

Crash Report 2.3.1.8 
Please submit a bug report with the following information. 

System.IO.FileNotFoundException: Could not find file 'C:\Users\Estefania\Documents/TexTools/Saved'.
File name: 'C:\Users\Estefania\Documents/TexTools/Saved'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at FFXIV_TexTools.ViewModels.MainViewModel.SetDirectories(Boolean valid)
   at FFXIV_TexTools.ViewModels.MainViewModel..ctor(MainWindow mainWindow)
   at FFXIV_TexTools.MainWindow..ctor(String[] args)
   at FFXIV_TexTools.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Squall-Leonhart** [comment]
Turn off Controlled Folder Access or add FFXIV_TexTools.exe to its whitelist

https://www.tenforums.com/tutorials/113380-enable-disable-controlled-folder-access-windows-10-a.html
