### ISSUE TITLE
Unable to pull up a 3d model on my textools

### ISSUE THREAD

**Issue by AkiraMato154** [TexTools/FFXIV_TexTools_UI#222]
(I'm not sure if I was supposed to post this error I just thought that was what It was telling me to do but mainly the 3d models in textools are no longer showing up) 

System.NullReferenceException: Object reference not set to an instance of an object.
   at HelixToolkit.Wpf.SharpDX.Model.Scene.ScreenSpacedNode.OnHitTest(HitTestContext context, Matrix totalModelMatrix, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.ViewBoxNode.OnHitTest(HitTestContext context, Matrix totalModelMatrix, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.SceneNode.HitTest(HitTestContext context, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.ViewBoxHitTest(Point p, InputEventArgs originalInputEventArgs)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.MouseDownHitTest(Point pt, InputEventArgs originalInputEventArgs)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.OnPreviewMouseDown(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FFXIV_TexTools.App.Main()
(I'm not sure if I was supposed to post this error I just thought that was what It was telling me to do)

**Comment by Squall-Leonhart** [comment]
Despite other reports of this issue occurring, there has been no cause identified in textools itself and it appears to be some form of Windows corruption.

**Comment by JamiesonC** [comment]
I am also experiencing HelixToolkit exceptions any time 3D content is to be displayed. May be the same root cause or may be a different issue. Will start here. Note that I am running TexTools under Wine, which introduces additional variables.

![image](https://user-images.githubusercontent.com/1937578/225401414-76eb9ed7-b41c-4865-ac8d-4ceb4d031cfe.png)

**Comment by Squall-Leonhart** [comment]
Wine is not and will not be supported.

**Comment by crankygank** [comment]
Has there been any updates to this issue by chance? 

I have just reinstalled textools after reinstalling my OS and now textools is giving me this error.

**Comment by Squall-Leonhart** [comment]
theres been no updates for this issue because from our end everything is fine, the error is possibly occuring in Helix itself due to an issue with the state of the OS

Possible Solutions
* checking for updates for the installed video drivers for both dgpu and igp
* installing the full june 2010 dx redist
* disabling, removing or updating applications that run an overlay server.
* uninstalling / disabling nahimic

**Comment by crankygank** [comment]
so after doing some messing around, i eventually took out one of my graphics cards (i have two in my pc as I run quite a few monitors). Taking out one of the graphics cards got the 3d models to show. The addition of the graphics card back in broke the 3d viewer. 

Both cards are updated to the latest possible drivers. I have attempted to then dedicated one card to the program in every way possible and still run into the 3d issue running dual cards.

**Comment by Dreambourne** [comment]
Thank you Cranky gank I was having the same issue! I unplugged one of my monitors and viola my models loaded.
