### ISSUE TITLE
Problems using FMV and loading gear models

### ISSUE THREAD

**Issue by TheGuyCalledBob** [TexTools/FFXIV_TexTools_UI#228]
Got the following and it asked that I submit a bug report. Had 3 instances of this pop-up back to back when the issue occurred. Initially, only the gear would not load, and Viera models went to FMV okay, but after the first reinstall that started throwing errors too.
STEPS TRIED:
- Removing modpacks
- Uninstall/Reinstall
- Run as administrator

System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt16(Byte[] value, Int32 startIndex)
   at xivModdingFramework.Models.DataContainers.ExtraSkeletonEntry.Read(Byte[] data, UInt32 count, UInt32 index)
   at xivModdingFramework.Models.FileTypes.Est.<GetEstFile>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Models.FileTypes.Est.<GetExtraSkeletonEntry>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Models.FileTypes.Sklb.<GetExtraSkelbPath>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Models.FileTypes.Sklb.<GetExtraSkeletonFile>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at xivModdingFramework.Models.DataContainers.TTModel.<>c__DisplayClass44_0.<<ResolveBoneHeirarchyRaw>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at xivModdingFramework.Models.DataContainers.TTModel.ResolveBoneHeirarchyRaw(List`1 roots, XivRace race, List`1 bones, Action`2 loggingFunction)
   at xivModdingFramework.Models.DataContainers.TTModel.ResolveFullBoneHeirarchy(XivRace race, List`1 models, Action`2 loggingFunction)
   at FFXIV_TexTools.ViewModels.FullModelViewport3DViewModel.GetBoneDictionary(XivRace race)
   at FFXIV_TexTools.ViewModels.FullModelViewport3DViewModel.MakeHelixBones(XivRace targetRace)
   at FFXIV_TexTools.ViewModels.FullModelViewport3DViewModel.AddSkeletonNode(XivRace targetRace)
   at FFXIV_TexTools.ViewModels.FullModelViewport3DViewModel.RemoveModel(String modelItemType)
   at FFXIV_TexTools.ViewModels.FullModelViewport3DViewModel.UpdateModel(TTModel model, Dictionary`2 textureDataDictionary, IItemModel item, XivRace modelRace, XivRace targetRace)
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<AddModelToView>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FFXIV_TexTools.App.Main()
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt16(Byte[] value, Int32 startIndex)
   at xivModdingFramework.Models.DataContainers.ExtraSkeletonEntry.Read(Byte[] data, UInt32 count, UInt32 index)
   at xivModdingFramework.Models.FileTypes.Est.<GetEstFile>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Models.FileTypes.Est.<GetExtraSkeletonEntry>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Models.FileTypes.Sklb.<GetExtraSkelbPath>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Models.FileTypes.Sklb.<GetExtraSkeletonFile>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at xivModdingFramework.Models.DataContainers.TTModel.<>c__DisplayClass44_0.<<ResolveBoneHeirarchyRaw>b__0>d.MoveNext()<---

**Comment by Squall-Leonhart** [comment]
This is an issue with your game data, join the textools discord for assistance
