### ISSUE TITLE
[Bug]: Crashes when I try to open the Hair Defined Mod file

### ISSUE THREAD

**Issue by CivilizationAce** [TexTools/FFXIV_TexTools_UI#251]
### Expected behavior?

A list of stuff.

### Actual behavior?

It crashes. Error message included below.

Note that I'm going to check the flag at the bottom, as there are no clues given to how to confirm anything. How could I possibly know whether it's bad game data?

### Steps to reproduce the problem

1. Download latest version of the mod .7z file
2. Unzip it using 7-zip
3. Run TexTools
4. Click on Mods, then import mod files
5. Select the unzipped file. Wait a few seconds (under 10 I think).
...

### Error messages?

======================================================
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at xivModdingFramework.Mods.FileTypes.TTMP.<>c__DisplayClass15_0.<GetOriginalModPackJsonData>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.Views.SimpleModPackImporter.<ImportOldModPack>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.Views.SimpleModPackImporter.<Initialize>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
======================================================

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Hair Defined.ttmp2

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
And i'm going to close this issue because

1> its an issue with your game data
2> you have not been in contact with anyone inside the discord at all, where there are more tools and means to assist in resolving the issue.

**Comment by CivilizationAce** [comment]
I used the Discord link, but I must be in the wrong place. This is what I found:
