### ISSUE TITLE
[Bug]: TT crashes when switching character race inside FMV 

### ISSUE THREAD

**Issue by gregest** [TexTools/FFXIV_TexTools_UI#262]
### Expected behavior?

Switch to the race without crashing

### Actual behavior?

Texttools loads for very long, then throws out an error and then crashes 

### Steps to reproduce the problem

1. Try to export outfit through FMV 
2. Switch race 
3. Crash

### Error messages?

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Exception: Encountered an error while updating body textures.

Error: The given key was not present in the dictionary.
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateBodyTextures>d__111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateAllSkin>d__106.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: Encountered an error while updating body textures.

Error: The given key was not present in the dictionary.
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateBodyTextures>d__111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FFXIV_TexTools.ViewModels.FullModelViewModel.<UpdateAllSkin>d__106.MoveNext()<---

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: Exporting through FMV 
Item: Modded Omega-f Attire 

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by gregest** [comment]
apologies, it wasn't an actual issue when I thought it was
