### ISSUE TITLE
[Bug]: Literally cant even open textools, despite completely removing all files & redownloading

### ISSUE THREAD

**Issue by CrowleysCreation** [TexTools/FFXIV_TexTools_UI#276]
### Expected behavior?

Actually open the application

### Actual behavior?

Yeetus Deletus application existence. "everything put prior & after"

### Steps to reproduce the problem

1. I have absolutely no idea other than it randomly happened. After first install it wont even show the error page.
2.
3.
4.
5.
...

### Error messages?

Error encountered when initially launching after completely removing files and retrying to download it.

System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 12, position 1. (C:\Users\Redux\AppData\Local\FFXIV_TexTools\FFXIV_TexTools.exe_Url_1qwuoz3ib42y0nj5ftyu4gjckzkkruui\2.3.8.2\user.config line 12) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 12, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at FFXIV_TexTools.MainWindow.CheckForSettingsUpdate()
   at FFXIV_TexTools.MainWindow..ctor(String[] args)
   at FFXIV_TexTools.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)
Mostly only used it for finding model paths.

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by CrowleysCreation** [comment]
This has persisted for about half a year i think.

**Comment by Squall-Leonhart** [comment]
You would have gotten quicker help had you joined the discord, delete the config file at the location in the error and it'll restore it from the last working version.
