### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BangCockk** [TexTools/FFXIV_TexTools_UI#279]
### Expected behavior?

/

### Actual behavior?

/

### Steps to reproduce the problem

1./
2.
3.
4.
5.
...

### Error messages?

System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at xivModdingFramework.Exd.FileTypes.Ex.<ReadExData>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Items.Categories.Gear.<GetUnCachedGearList>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Cache.XivCache.<RebuildGearCache>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Cache.XivCache.<RebuildItemsCache>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Cache.XivCache.<>c__DisplayClass30_0.<<RebuildCache>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at xivModdingFramework.Cache.XivCache.RebuildCache(Version previousVersion, CacheRebuildReason reason)
   at xivModdingFramework.Cache.XivCache.SetGameInfo(GameInfo gameInfo, Boolean enableCacheWorker)
   at FFXIV_TexTools.MainWindow..ctor(String[] args)
   at FFXIV_TexTools.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at xivModdingFramework.Exd.FileTypes.Ex.<ReadExData>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Items.Categories.Gear.<GetUnCachedGearList>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Cache.XivCache.<RebuildGearCache>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Cache.XivCache.<RebuildItemsCache>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xivModdingFramework.Cache.XivCache.<>c__DisplayClass30_0.<<RebuildCache>b__0>d.MoveNext()<---

### What aspect of FFXIV TexTools were you using, and what Item were you interacting with?

Component: (Full model  viewer, Item Converter, Importer, Modpack Creator (and which one), etc)
Item: (Gear, Race, Furnishing, etc)

### Has this has been confirmed as an actual bug?

- [X] This has been confirmed to be a legitimate issue and not caused by bad game data.

**Comment by Squall-Leonhart** [comment]
not a valid report, and most likely bad game data
