### ISSUE TITLE
Im not even sure what to label this error

### ISSUE THREAD

**Issue by KingKusho** [TexTools/FFXIV_TexTools_UI#65]
whenever i try to activate a mod i get this message. ive been running mods for about a year now and this is the first time iv ever had any issues. totally a noob not sure what to do.

System.InvalidOperationException: GetModlist returned NULL Mod List.
   at xivModdingFramework.Mods.Modding.GetModList()
   at xivModdingFramework.Mods.Modding.<>c__DisplayClass13_0.<TryGetModEntry>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.Views.Metadata.MetadataView.<SetRoot>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.Views.Metadata.MetadataView.<SetItem>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.MainWindow.<UpdateViews>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by KoraLyn** [comment]
Your modlist is missing somehow. If you were able to run the program just fine before then it's more likely that TexTools isn't pointing at the correct game folder so please double check that first. You can run a check for problems to have TexTools attempt to repair it if that's not the case.

**Comment by KoraLyn** [comment]
Assuming this has been resolved, closing the issue.
