### ISSUE TITLE
Unable to rebuild cache

### ISSUE THREAD

**Issue by ZeoRed** [TexTools/FFXIV_TexTools_UI#88]
My textools was working fine 3 days ago, but suddenly when launching it, I've encountered this error:

An error occurred while attempting to rebuild the cache. This may be caused by this version of Final Fantasy XIV not being supported by this version of TexTools.

![image](https://user-images.githubusercontent.com/89498485/130870923-ab204cb4-347f-48f6-9000-d4b947727e98.png)

When trying to rebuild cache or start over, I get the same error. I can't import any of my previous modpacks either. I've tried uninstalling and reinstalling TexTools multiple times but I keep getting the same error. FF14 works just fine, but I reinstalled it to try it out and have had no success. I tried doing some online research and reinstalled .NET Framework 2.0, 3.0, 5.0 but also to no success. 

One one attempt at rebuilding cache, I got this:
 System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.

I also got this longer error message once

System.AggregateException: One or more errors occurred. ---> System.BadImageFormatException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1) ---> System.BadImageFormatException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1) ---> System.BadImageFormatException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Transactions.Transaction.JitSafeGetContextTransaction(ContextData contextData)
   at System.Transactions.Transaction.FastGetTransaction(TransactionScope currentScope, ContextData contextData, Transaction& contextTransaction)
   at System.Transactions.Transaction.get_Current()
   at System.Data.SQLite.SQLiteConnection.Open()
   at xivModdingFramework.Cache.XivCache.CreateCache()
   at xivModdingFramework.Cache.XivCache.<>c__DisplayClass30_0.<<RebuildCache>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at xivModdingFramework.Cache.XivCache.RebuildCache(Version previousVersion, CacheRebuildReason reason)
   at xivModdingFramework.Cache.XivCache.SetGameInfo(GameInfo gameInfo, Boolean enableCacheWorker)
   at FFXIV_TexTools.ViewModels.MainViewModel.SetDXVersion(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) System.BadImageFormatException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'System.EnterpriseServices.Wrapper.dll' ---> System.BadImageFormatException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'System.EnterpriseServices.Wrapper.dll' ---> System.BadImageFormatException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'System.EnterpriseServices.Wrapper.dll'

   at System.Transactions.Transaction.JitSafeGetContextTransaction(ContextData contextData)
   at System.Transactions.Transaction.FastGetTransaction(TransactionScope currentScope, ContextData contextData, Transaction& contextTransaction)
   at System.Transactions.Transaction.get_Current()
   at System.Data.SQLite.SQLiteConnection.Open()
   at xivModdingFramework.Cache.XivCache.CreateCache()
   at xivModdingFramework.Cache.XivCache.<>c__DisplayClass30_0.<<RebuildCache>b__0>d.MoveNext()

**Comment by ZeoRed** [comment]
I fixed it by doing a windows update in place using the windows media tool creator
