### ISSUE TITLE
Textool crashes when Importing Mod. Tried rebuilding cache and re-installing.

### ISSUE THREAD

**Issue by KaleidoscopeOnion** [TexTools/FFXIV_TexTools_UI#98]
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at xivModdingFramework.Mods.FileTypes.TTMP.<>c__DisplayClass14_0.<GetOriginalModPackJsonData>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.Views.SimpleModPackImporter.<ImportOldModPack>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_TexTools.Views.SimpleModPackImporter.<Initialize>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Squall-Leonhart** [comment]
the ttmp is corrupt or is not a complete download.

**Comment by KaleidoscopeOnion** [comment]
> the ttmp is corrupt or is not a complete download.

How do I fix it though? It’s Hair Defined and I’m downloading it right off Nexus

**Comment by Squall-Leonhart** [comment]
download it with another web browser, works fine here.
